### ISSUE TITLE
Feature request: show link to tip

### ISSUE THREAD

**Issue by pdgonzalez872** [elixirstream/elixirstream.dev#3]
Thanks for doing this! :heart: 

I wanted to link to a tip I found on the app and didn't really have a way to do that. We create links for the poster (github and twitter) but not the tip itself, so I can't share it :(

What do you think?

**Comment by dbernheisel** [comment]
Sounds great :) That's probably an oversight. I'll see if I can get that today.

**Comment by pdgonzalez872** [comment]
:heart:

**Comment by dbernheisel** [comment]
The link isn't apparent, but now you can click the title of the tip.
I also want to get a Share button on the card for easier sharing. If you have any ideas around that, let me know!

**Comment by pdgonzalez872** [comment]
:+1: 

I like when you can click something and it copies to the clipboard. That will make sharing links simple :)
